// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_captain_shield = "CgkIoPzSm_sFEAIQBg"; // <GPGSID>
        public const string achievement_competitor_shield = "CgkIoPzSm_sFEAIQDQ"; // <GPGSID>
        public const string achievement_invincible_player_award = "CgkIoPzSm_sFEAIQDg"; // <GPGSID>
        public const string achievement_admiral_shield = "CgkIoPzSm_sFEAIQCg"; // <GPGSID>
        public const string achievement_lieutenant_commander_shield = "CgkIoPzSm_sFEAIQBA"; // <GPGSID>
        public const string achievement_commodore_shield = "CgkIoPzSm_sFEAIQBw"; // <GPGSID>
        public const string achievement_daring_kitty = "CgkIoPzSm_sFEAIQDA"; // <GPGSID>
        public const string leaderboard_global_rankings = "CgkIoPzSm_sFEAIQAQ"; // <GPGSID>
        public const string achievement_admiral_of_the_fleet_shield = "CgkIoPzSm_sFEAIQCw"; // <GPGSID>
        public const string achievement_commander_shield = "CgkIoPzSm_sFEAIQBQ"; // <GPGSID>
        public const string achievement_sub_lieutenant_shield = "CgkIoPzSm_sFEAIQAg"; // <GPGSID>
        public const string achievement_vice_admiral_shield = "CgkIoPzSm_sFEAIQCQ"; // <GPGSID>
        public const string achievement_lieutenant_shield = "CgkIoPzSm_sFEAIQAw"; // <GPGSID>
        public const string achievement_rear_admiral_shield = "CgkIoPzSm_sFEAIQCA"; // <GPGSID>

}

